FROM quay.io/toolbx/ubuntu-toolbox:25.04

ARG NAME=ubuntu-reseau
ARG VERSION=25.04
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Ubuntu 25.04 image for self hosted server development"

RUN apt-get update \
  && apt-get install -y \
    apt-transport-https \
    curl \
    ubuntu-keyring \
    fzf \
    pipx \
    python3 \
    software-properties-common \
    vim \
    zoxide \
  && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-xcaddy-archive-keyring.gpg \
  && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-xcaddy.list \
  && wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list \
  && apt-get update \
  && pipx ensurepath \
  && pipx ensurepath --global \
  && apt-get install -y \
    terraform \
    xcaddy \
  && pipx install --global --include-deps ansible \
  && apt-get autoremove -y



