FROM quay.io/fedora/fedora-toolbox:42

ARG NAME=fedora-42-bpf
ARG VERSION=42
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Fedora 42 image focused on building eBPF programs"

RUN dnf --assumeyes install \
	fzf zoxide \
	bear bpftool clang clang-tools-extra cmake libbpf-devel make \
	vim \
	--setopt=install_weak_deps=false
RUN dnf clean all
